---
- name: using tags in ansible
  hosts: all
  tasks:
   - name: install tomcat8
     apt:
      name: tomcat8
      state: present
     tags: install_software
   - name: create file in manged nodes
     file:
      name: file1
      state: touch
     tags: create_file
   - name: check url respone
     uri:
      url: "{{item}}"
      status_code: 200
     with_items:
      - http://172.31.37.140

