version: '3'
services:
 devserver:
  image: jenkins
  ports:
   - 5050:8080
  deploy:
   placement:
    constraints:
     - node.hostname==devserver
 qaserver:
  image: tomcat
  ports: 
   - 6060:8080
  deploy:
   replicas: 2
   placement:
    constraints: 
     - node.hostname==qaserver
 prodserver:
  image: tomcat
  ports:
   - 7070:8080
  deploy:
   replicas: 2
   placement:
    constraints:
     - node.hostname==prodserver
